on:
  push:
    branches:
      - main

jobs:
  bump-tag-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for tags and changelog

      - name: Set up Git config
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          TAG=$(git tag -l 'v*' | sort -V | tail -n 1)
          echo "Latest tag: $TAG"
          if [ -z "$TAG" ]; then
            TAG="v0.0.0"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Bump version (patch)
        id: bump
        run: |
          VERSION="${{ steps.get_tag.outputs.tag }}"
          VERSION="${VERSION#v}"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          # Default: bump patch
          PATCH=$((PATCH + 1))

          NEW_TAG="v${MAJOR}.${MINOR}.${PATCH}"
          echo "Bumping to: $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Get changelog since last tag
        id: changelog
        run: |
          LOG=$(git log ${{ steps.get_tag.outputs.tag }}..HEAD --pretty=format:"- %s")
          echo "changelog<<EOF" >> $GITHUB_ENV
          echo "$LOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git tag "${{ steps.bump.outputs.new_tag }}"
          git push origin "${{ steps.bump.outputs.new_tag }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          name: Release ${{ steps.bump.outputs.new_tag }}
          body: ${{ env.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
